### ISSUE TITLE
Unable to use 2DS+capture with Cute3DSCapture

### ISSUE THREAD

**Issue by 3snowp7im** [Gotos/Cute3DSCapture#1]
Hi Gotos, thanks very much for writing this. I received a 2DS+capture today and was wondering if I'd be able to use this for capture on a linux PC. The first thing I noticed was that my capture board seems to be a different device:

Bus 005 Device 011: ID 04b4:8613 Cypress Semiconductor Corp. CY7C68013 EZ-USB FX2 USB 2.0 Development Kit

(output from lsusb)

I tried running the software as it's checked in, and with the new VID and PID of my device, but I'm not getting any captured images from the 2DS with either (just garbled video buffer).

Any advice? I don't have much experience dealing with dev usb boards.

**Comment by Gotos** [comment]
Hi!

Unfortunately the 2DS capture unit is a very different device which I do not support right now. I'd like to get one to rewrite C3C to work with it, but unfortunately I can not afford one right now. So for now you won't be able to use the software :C
(Also, is that a capture board by loopy? The name of the board seems oddly different and I thought loopy hasn't released 2DS boards)
