### ISSUE TITLE
Updated macOS build

### ISSUE THREAD

**Issue by vgmoose** [Gotos/Cute3DSCapture#3]
I have rebuilt Cute3DSCapture to run on newer macOS versions, like Catalina. The download for this version is [here](https://github.com/vgmoose/Cute3DSCapture/releases/tag/v1.3.2mac).

The process to bundle libusb and sfml into the binary in order to make it run without having to setup brew first is as follows (most of this I got from following the [instructions here](http://thecourtsofchaos.com/2013/09/16/how-to-copy-and-relink-binaries-on-osx/)):
```bash
# get needed dependencies
brew install libusb sfml

# actually build cute3dscapture
./autogen.sh && ./configure && make

# copy these dynamic libs over to be bundled
cp /usr/local/opt/libusb/lib/libusb-1.0.0.dylib /usr/local/opt/sfml/lib/libsfml-window.2.5.dylib /usr/local/opt/sfml/lib/libsfml-graphics.2.5.dylib /usr/local/opt/sfml/lib/libsfml-system.2.5.dylib .

# these are inter-deps that we'll need later as well
cp /usr/local/opt/libpng/lib/libpng16.16.dylib /usr/local/opt/freetype/lib/libfreetype.6.dylib .

# edit binary to have libusb and sfml relatively linked
# (can check with otool -L Cute3DSCapture to see current dylib paths)
install_name_tool -change /usr/local/opt/libusb/lib/libusb-1.0.0.dylib @executable_path/libusb-1.0.0.dylib Cute3DSCapture
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-window.2.5.dylib @executable_path/libsfml-window.2.5.dylib Cute3DSCapture
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-graphics.2.5.dylib @executable_path/libsfml-graphics.2.5.dylib Cute3DSCapture
install_name_tool -change /usr/local/opt/sfml/lib/libsfml-system.2.5.dylib @executable_path/libsfml-system.2.5.dylib Cute3DSCapture

# adjust some of the dylibs to internally reference these relative dylibs as well
# (can also check with otool -L <dylib>)
install_name_tool -change @rpath/libsfml-window.2.5.dylib @executable_path/libsfml-window.2.5.dylib ./libsfml-graphics.2.5.dylib
install_name_tool -change @rpath/libsfml-system.2.5.dylib @executable_path/libsfml-system.2.5.dylib ./libsfml-graphics.2.5.dylib
install_name_tool -change @rpath/libsfml-system.2.5.dylib @executable_path/libsfml-system.2.5.dylib ./libsfml-window.2.5.dylib

# some more inter-dependent dylibs
install_name_tool -change /usr/local/opt/libpng/lib/libpng16.16.dylib @executable_path/libpng16.16.dylib ./libfreetype.6.dylib
install_name_tool -change /usr/local/opt/freetype/lib/libfreetype.6.dylib @executable_path/libfreetype.6.dylib ./libsfml-graphics.2.5.dylib

# make app bundle (can find other resources on how to make the Info.plist or app bundle, but the dylibs can go in Contents/MacOS now)
mkdir -p Cute3DSCapture.app/Contents/MacOS
cp Cute3DSCapture *.dylib Cute3DSCapture.app/Contents/MacOS
cp Info.plist Cute3DSCapture.app/Contents
```

After that, the app bundle would need to be notarized by Apple to allow it to run without needing to go through Gatekeeper. Is there a license this code is available under? It could be possible to publish Cute3DSCapture to the Mac App Store to make installing easier.

I would also be interested in helping getting automated builds for mac/linux working via something like travis or circle CI, so that there's not a dependency on someone needing a physical Mac to build it.

**Comment by vgmoose** [comment]
By the way thank you for this app! It's very easy to use.

**Comment by Gotos** [comment]
Hi!

Thanks for putting the work into this!
I have been asked for a license on this year ago, but never got around to choosing one. As I'm a bit more familiar with licensing due to my job now, I think I feel like I can choose now. I'm at my lunch break right now, but I'll try to remember having a look at this in the evening or on the weekend.

Besides that, I would very much be interested in using CI for the builds. It's nothing I'm very familiar with, but if you could help with that, I'd be more than happy about that.

**Comment by Gotos** [comment]
I researched a bit - it seems apple does not allow GPL-licensed software in their app store? (At least not without a secondary license for their store)
Do you happen to have experience with that topic already? Any licenses you know should be fine by Apple? (And yes, I'm aware you're most likely not qualified to give legal advise ;) I'm just looking for experience with development for the app store.)

**Comment by vgmoose** [comment]
It does seem like Apple doesn't want people going around and uploading GPL apps, so I wouldn't be surprised if I would need special license/permission from you to host it. But we could try it anyway to see if they say something. I think the issue with GPL is usually more that any contributor could object to the distribution, and it would be hard to get permission from all the contributors.

Since you are the primary developer it's probably a lot easier for you to say that I would have permission (could be revocable too) to publish the app on the mac store. For me, I have a GPL app but I'm also the sole author so I'm always owning the full copyright on it anyway. (Which would technically/legally be [multi-licensing](https://en.wikipedia.org/wiki/Multi-licensing), I think)

There's also the issue that Apple may reject it for other reasons since they're pretty picky 😛 I should note that the build I linked has already been notarized by them under my developer account so from a technical prospect it seems like they aren't objecting to libusb.

For the CI I'll try to get a PR going! I have also verified that this build does work with someone who owns a 3ds capture card on Catalina, only the notarizing is the concern which the store would solve.

**Comment by Gotos** [comment]
Short update: I unfortunately have been away from home for the last month and didn't get around to updating the license so far. Sorry about that. Apparently every time I try to work on this project, something comes up that is more urgent. Haven't forgotten about this tho, and I'll be home soon. I hope to actually get around to this on the weekend.

**Comment by vgmoose** [comment]
No worries! I also got caught up in some other stuff and haven’t gotten around to trying to submit to Apple, nor have I started the CI yet 😅

**Comment by Gotos** [comment]
Cute3DSCapture is now licensed under the Apache License 2.0. Hope this helps with the potential release at the Apple Store. :)
I'll keep this issue open until that worked out. For the CI, let's get that in a separate discussion. Just create a Pull Request once you start work on that and we can discuss there, if you need anything from me for that :)

**Comment by vgmoose** [comment]
Made a PR for the CI changes in #8, which can also be adapted to build CDC as well if merging the codebases!

For Mac App Store submission, any thoughts on an icon that doesn't have Nintendo's official 3DS logo in it? I noticed when the app is running it sets the following:

<img width="39" alt="Screen Shot 2020-10-12 at 4 26 27 PM" src="https://user-images.githubusercontent.com/2467473/95787795-3cdbaa00-0ca8-11eb-96cc-f3da6008d132.png">

Which seems like a decent alternative candidate / art direction, but is too low resolution to use as the app's icon.

**Comment by Gotos** [comment]
I'm not sure if there is a higher quality version of it... I do remember making an svg for that before but I'm not sure if that's still around. I'll check!

**Comment by Gotos** [comment]
I've looked for the icon, but the one I remembered was a) not an svg, just a bigger image and b) it wasn't this logo but a logo that used parts of the official 3DS logo. So I'm afraid there is no higher resolution version of this icon.

What resolution would you need?

**Comment by vgmoose** [comment]
1024x1024 would be best, but 512x512 would work as well

**Comment by Gotos** [comment]
Close because I merged the pull request. The icon topic has its own issue now, #9 - I think that was all that we discussed here that isn't implemented yet, right?
