### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by Bappsack** [Gotos/Cute3DSCapture#6]
will it ever support windows? the official one have sorta issues with multiple devices since we can't select a COM port manually.

**Comment by Gotos** [comment]
That's not really planned. I doubt that C3C wouldn't have a problem with multiple devices tho. As I don't have multiple modded 3DS' and I didn't really plan to continue work on this (until recently interest in it spiked, for whatever reason o0), I can't test this either.
If someone familiar with Windows development is willing to port it, I'd be happy to receive Pull Requests tho!
